name: CI

on: [push]

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              name: Use Node.js
              with:
                node-version: "14"

            - name: Install bun
              run: npm install -g bun

            - name: Install dependencies
              run: bun run ci

            - name: Format Code
              run: bun run format

            - name: Run linter
              env:
                CLERK_SECRET_KEY: ${{ env.CLERK_SECRET_KEY }}
                NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
              run: bun run lint